### ISSUE TITLE
SP617E setup and can control initially, but becomes unavailable after some time.

### ISSUE THREAD

**Issue by loopy321** [monty68/uniled#36]
The device setups correctly and I can control it in HA, but it goes unavailable after some time.  This is uniled v. 1.04 on HA 2023.08.4

```
2023-11-11 19:44:57.078 ERROR (MainThread) [custom_components.uniled.coordinator] Unexpected error fetching 21:06:27:00:E1:33 data: 'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uniled/coordinator.py", line 88, in _async_update
    if not await self.device.update():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uniled/lib/ble_device.py", line 127, in update
    if not await self.send_command(self.model.construct_status_query(self)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uniled/lib/ble_device.py", line 229, in send_command
    await self._send_command_while_connected(commands, retry)
  File "/config/custom_components/uniled/lib/ble_device.py", line 297, in _send_command_while_connected
    await self._send_command_locked(commands)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 471, in _async_wrap_bluetooth_connection_error_retry
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uniled/lib/ble_device.py", line 326, in _send_command_locked
    await self._execute_command_locked(commands)
  File "/config/custom_components/uniled/lib/ble_device.py", line 359, in _execute_command_locked
    await self._client.write_gatt_char(self._write_char, command, None)
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 659, in write_gatt_char
    await self._backend.write_gatt_char(char_specifier, data, response)
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 83, in _async_wrap_bluetooth_connected_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 97, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 642, in write_gatt_char
    await self._client.bluetooth_gatt_write(
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 861, in bluetooth_gatt_write
    req.response = response
    ^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
2023-11-11 19:44:57.082 DEBUG (MainThread) [custom_components.uniled.coordinator] Finished fetching 21:06:27:00:E1:33 data in 0.503 seconds (success: False)
2023-11-11 19:44:57.082 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Stop
2023-11-11 19:44:57.082 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Disconnecting from device
2023-11-11 19:44:57.083 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Stopped notifications from device
2023-11-11 19:44:57.162 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Disconnected from device
2023-11-11 19:44:57.162 WARNING (MainThread) [homeassistant.config_entries] Config entry 'SP617E' for uniled integration not ready yet: 'NoneType' object cannot be interpreted as an integer; Retrying in background
2023-11-11 19:44:57.163 DEBUG (MainThread) [custom_components.uniled] *** Setup UniLED BLE Device: 21:06:27:00:E1:33: None v1 - ({'device_class': 'ble', 'address': '21:06:27:00:E1:33', 'model': 'SP617E'}), Service: <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f087e0ecec0>
2023-11-11 19:44:57.164 DEBUG (MainThread) [custom_components.uniled.lib.classes] 21:06:27:00:E1:33: Init Channel 0
2023-11-11 19:44:57.164 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] None: Init BLE Device (Model: SP617E)
2023-11-11 19:44:57.164 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Set model SP617E
2023-11-11 19:44:57.164 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Update
2023-11-11 19:44:57.164 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Connecting; RSSI: -66
2023-11-11 19:44:57.274 DEBUG (MainThread) [custom_components.uniled.coordinator] Coordinator destroyed
2023-11-11 19:44:57.657 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Connected
2023-11-11 19:44:57.657 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Read Characteristic: 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 3): Vendor specific
2023-11-11 19:44:57.657 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Write Characteristic: 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 3): Vendor specific
2023-11-11 19:44:57.657 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Subscribe to notifications: 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 3): Vendor specific
2023-11-11 19:44:57.696 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Sending 1 command(s)
2023-11-11 19:44:57.697 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] 21:06:27:00:E1:33: Sending command: [a07000] 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 3): Vendor specific
2023-11-11 19:44:57.697 ERROR (MainThread) [custom_components.uniled.coordinator] Unexpected error fetching 21:06:27:00:E1:33 data: 'NoneType' object cannot be interpreted as an integer

```

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by loopy321** [comment]
Updated to HA 2023.11.2 and seems to fix it.
