### ISSUE TITLE
After upgrading to v2.2.1, the SP601E is not working

### ISSUE THREAD

**Issue by VasiliyNovosad** [monty68/uniled#49]
## Version of the custom_component
UniLED v2.2.1, HA Core 2024.1.3

## Describe the bug
After upgrading to v2.2.1, the SP601E is not working

## Debug log
```text

2024-01-19 12:50:04.679 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Checking support for: '55:55:07:05:8A:6E' (SP601E)... AdvertisementData(local_name='SP601E', manufacturer_data={20563: b'\x01\x01UU\x07\x05\x8an'}, rssi=-127)
2024-01-19 12:50:04.679 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Device '55:55:07:05:8A:6E' (SP601E) not supported!

```

**Comment by VasiliyNovosad** [comment]
After updating I faces the issue with initialization:

Debug logs:
```
2024-01-21 15:22:39.921 WARNING (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Update - Failed, notification timeout.
2024-01-21 15:22:39.922 DEBUG (MainThread) [custom_components.uniled.coordinator] Finished fetching SP601E data in 11.001 seconds (success: False)
2024-01-21 15:22:39.922 WARNING (MainThread) [custom_components.uniled] SP601E: First update attempt failed!
2024-01-21 15:22:39.922 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Stop
2024-01-21 15:22:39.923 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Executing forced disconnect
2024-01-21 15:22:39.923 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Executing disconnect
2024-01-21 15:22:39.923 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Executing disconnect with lock
2024-01-21 15:22:39.923 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Disconnecting '55:55:07:05:8A:6E'...
2024-01-21 15:22:42.519 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Disconnected from '55:55:07:05:8A:6E'.
2024-01-21 15:22:42.522 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Disconnecting '55:55:07:05:8A:6E' successful.
2024-01-21 15:22:42.522 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Stopped
2024-01-21 15:22:42.970 DEBUG (MainThread) [custom_components.uniled.coordinator] SP601E: Coordinator destroyed
2024-01-21 15:22:42.970 DEBUG (MainThread) [custom_components.uniled.lib.device] SP601E: Deleted Device
2024-01-21 15:22:42.970 DEBUG (MainThread) [custom_components.uniled.lib.channel] Deleted: channel_2
2024-01-21 15:22:42.970 DEBUG (MainThread) [custom_components.uniled.lib.channel] Deleted: channel_1
2024-01-21 15:22:42.970 DEBUG (MainThread) [custom_components.uniled.lib.channel] Deleted: channel_0
2024-01-21 15:22:42.973 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Checking support for: '55:55:07:05:8A:6E' (SP601E)... AdvertisementData(local_name='SP601E', manufacturer_data={20563: b'\x01\x01UU\x07\x05\x8an'}, service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-69)
2024-01-21 15:22:42.973 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] Device 'SP601E' (55:55:07:05:8A:6E) is supported!
2024-01-21 15:22:42.975 DEBUG (MainThread) [custom_components.uniled] *** Setup UniLED BLE Device: 55:55:07:05:8A:6E: SP601E v3 - {'transport': 'ble', 'address': '55:55:07:05:8A:6E', 'model': 'SP601E'} AdvertisementData(local_name='SP601E', manufacturer_data={20563: b'\x01\x01UU\x07\x05\x8an'}, service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-69)
2024-01-21 15:22:42.975 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Inititalizing (SP601E)...
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Set model as 'SP601E' by SPLED (BanlanX)
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.channel] Inititalized: channel_0 (0xdd1b1d30)
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.channel] Inititalized: channel_1 (0xdd1b1b50)
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.channel] Inititalized: channel_2 (0xdd1b1270)
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Updated '55:55:07:05:8A:6E' advertisement; RSSI: -69
AdvertisementData(local_name='SP601E', manufacturer_data={20563: b'\x01\x01UU\x07\x05\x8an'}, service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-69)
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled] *** Awaiting UniLED Device: SP601E, first response...
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Update!
2024-01-21 15:22:42.976 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Update - Send State Query... (retrys=0)
2024-01-21 15:22:42.977 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Send 1 command(s), attempt 1 of 1...
2024-01-21 15:22:42.977 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Connecting '55:55:07:05:8A:6E'; RSSI: -69
2024-01-21 15:22:47.750 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Connected '55:55:07:05:8A:6E'; RSSI: -69
2024-01-21 15:22:48.152 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Subscribe to '55:55:07:05:8A:6E' notifications: 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 12): Vendor specific
2024-01-21 15:22:48.514 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Sending command: aa2f00
2024-01-21 15:22:48.739 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Update - Awaiting 5.0 seconds for status notification...
2024-01-21 15:22:48.785 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Notification from '55:55:07:05:8A:6E' [12],
Data: 534301170f010100ff011e01ff000010010102ff
2024-01-21 15:22:49.054 DEBUG (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Notification from '55:55:07:05:8A:6E' [12],
Data: 5343021708011e0000ff001000
2024-01-21 15:22:49.054 DEBUG (MainThread) [custom_components.uniled.lib.ble.banlanx_601] SP601E: Message: 010100ff011e01ff000010010102ff011e0000ff001000
2024-01-21 15:22:49.054 DEBUG (MainThread) [custom_components.uniled.lib.ble.banlanx_601] SP601E: Channel 1: 010100ff011e01ff000010
2024-01-21 15:22:49.055 DEBUG (MainThread) [custom_components.uniled.lib.ble.banlanx_601] SP601E: Channel 2: 010102ff011e0000ff0010
2024-01-21 15:22:49.055 DEBUG (MainThread) [custom_components.uniled.lib.ble.banlanx_601] SP601E: Residual : 00
2024-01-21 15:22:49.055 WARNING (MainThread) [custom_components.uniled.lib.ble.device] SP601E: Notification parser exception!
Traceback (most recent call last):
File "/config/custom_components/uniled/lib/ble/device.py", line 631, in _notification_handler
if self._model.parse_notifications(self, sender.handle, data) is True:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/uniled/lib/ble/banlanx_601.py", line 366, in parse_notifications
loop = True if data[1] != 0 else False
~~~~^^^
IndexError: bytearray index out of range
```
