### ISSUE TITLE
Faulty operation with SP641E

### ISSUE THREAD

**Issue by alexwhittemore** [monty68/uniled#61]
## Version of the custom_component
2.2.4

## Configuration

```yaml

Is there a way to view YAML configuration for things configured entirely in the GUI? 

```

## Describe the bug
My SP641E is set up correctly and entities are visible. I can slide the slider to set intensity just fine, but the "light" always shows "off". Using the toggle to turn it on/off fails with the following message, and even using the slider produces the same message, even though the LED dims appropriately as expected.

<img width="798" alt="image" src="https://github.com/monty68/uniled/assets/332827/ea149fcb-d576-45e6-8489-275a26406846">

## Debug log

```text
Logger: homeassistant
Source: components/light/__init__.py:1093
First occurred: February 17, 2024 at 3:23:19 PM (829 occurrences)
Last logged: 9:11:21 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/uniled/entity.py", line 250, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1129, in state_attributes
    self.__validate_color_mode(color_mode, legacy_supported_color_modes, effect)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1093, in __validate_color_mode
    effect_color_modes = supported_color_modes | {ColorMode.ONOFF}
                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for |: 'list' and 'set'


```

**Comment by alexwhittemore** [comment]
Totally fixed, thanks!

**Comment by alexwhittemore** [comment]
I might have spoken too soon - the entity card now has a simple toggle for the device rather than a slider for dimming. I can still set the brightness, but only by calling the Universal Light Controller: Set State service.
