### ISSUE TITLE
Unknown error occurred when I try add SP601E

### ISSUE THREAD

**Issue by VasiliyNovosad** [monty68/uniled#8]
I am trying to add SP601E controller to my Home Assistant, but getting error after initialization

## Version of the custom_component
0.2.2

## Describe the bug
After adding device I have got error on initialization "Retrying setup: SP601E: Data Update failed"

## Debug log

```text

2022-12-17 16:16:08.964 DEBUG (MainThread) [custom_components.uniled] *** Setup UniLED BLE Device: 55:55:07:05:8A:6E: SP601E v1 - ({'device_class': 'ble', 'address': '55:55:07:05:8A:6E', 'model': 'SP601E'})
2022-12-17 16:16:08.964 DEBUG (MainThread) [custom_components.uniled.lib.classes] SP601E: Init Channel 0
2022-12-17 16:16:08.965 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Init BLE Device (Model: SP601E)
2022-12-17 16:16:08.965 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Set model SP601E
2022-12-17 16:16:08.965 DEBUG (MainThread) [custom_components.uniled.lib.classes] SP601E: Init Channel 1
2022-12-17 16:16:08.966 DEBUG (MainThread) [custom_components.uniled.lib.classes] SP601E: Init Channel 2
2022-12-17 16:16:08.966 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Update device (RSSI: -37) AdvertisementData(local_name='SP601E', manufacturer_data={20563: b'\x01\x01UU\x07\x05\x8an'}, service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000ffe0-0000-1000-8000-00805f9b34fb'], rssi=-37)
2022-12-17 16:16:08.967 DEBUG (MainThread) [custom_components.uniled.coordinator] SP601E: Update, entry state: ConfigEntryState.SETUP_IN_PROGRESS
2022-12-17 16:16:08.967 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Update
2022-12-17 16:16:08.967 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Connecting; RSSI: -37
2022-12-17 16:16:15.410 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Connected
2022-12-17 16:16:15.410 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Read Characteristic: 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 12): Vendor specific
2022-12-17 16:16:15.410 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Write Characteristic: 0000ffe1-0000-1000-8000-00805f9b34fb (Handle: 12): Vendor specific
2022-12-17 16:16:15.411 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Subscribe to notifications
2022-12-17 16:16:15.848 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Sending 1 command(s)
2022-12-17 16:16:15.849 DEBUG (MainThread) [custom_components.uniled.lib.ble_retry] SP601E: Starting retry loop
2022-12-17 16:16:15.849 DEBUG (MainThread) [custom_components.uniled.lib.ble_retry] SP601E: Attempt 1
2022-12-17 16:16:15.849 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Sending command: aa2f00 
2022-12-17 16:16:16.140 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Awaiting status notification
2022-12-17 16:16:16.190 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Handle:12, notification data: 534301170f010100ff0a1e01ff000010010102ff
2022-12-17 16:16:16.433 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Handle:12, notification data: 53430217080a1e0000ff001000
2022-12-17 16:16:16.435 ERROR (MainThread) [root] A message handler raised an exception: can only concatenate tuple (not "bytearray") to tuple.
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 796, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 860, in _parse_msg
    on_value_changed(message.path, self_interface["Value"])
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 152, in on_value_changed
    callback(bytearray(value))
  File "/config/custom_components/uniled/lib/ble_device.py", line 200, in _notification_handler
    new_master_state = self._model.async_decode_notifications(
  File "/config/custom_components/uniled/lib/ble_banlanx1.py", line 147, in async_decode_notifications
    device.last_notification_data[5:] + data[5:]
TypeError: can only concatenate tuple (not "bytearray") to tuple

2022-12-17 16:16:18.142 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Timeout waiting for status notification
2022-12-17 16:16:18.143 DEBUG (MainThread) [custom_components.uniled.coordinator] Finished fetching SP601E data in 9.176 seconds (success: False)
2022-12-17 16:16:18.143 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Stop
2022-12-17 16:16:18.143 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Disconnecting from device
2022-12-17 16:16:18.151 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Stopped notifications from device
2022-12-17 16:16:20.119 DEBUG (MainThread) [custom_components.uniled.coordinator] Coordinator destroyed
2022-12-17 16:16:20.119 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] Device Destroyed
2022-12-17 16:16:20.120 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 2 Destroyed
2022-12-17 16:16:20.121 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 1 Destroyed
2022-12-17 16:16:20.121 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 0 Destroyed
2022-12-17 16:16:20.121 DEBUG (MainThread) [custom_components.uniled.coordinator] Coordinator destroyed
2022-12-17 16:16:20.122 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] Device Destroyed
2022-12-17 16:16:20.122 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 2 Destroyed
2022-12-17 16:16:20.122 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 1 Destroyed
2022-12-17 16:16:20.123 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 0 Destroyed
2022-12-17 16:16:20.123 DEBUG (MainThread) [custom_components.uniled.coordinator] Coordinator destroyed
2022-12-17 16:16:20.123 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] Device Destroyed
2022-12-17 16:16:20.124 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 2 Destroyed
2022-12-17 16:16:20.124 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 1 Destroyed
2022-12-17 16:16:20.124 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 0 Destroyed
2022-12-17 16:16:20.891 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Device disconnected (expected: True); RSSI: -37
2022-12-17 16:16:20.893 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Disconnected from device

```

**Comment by monty68** [comment]
Please download, install and test v0.2.3 Beta

**Comment by VasiliyNovosad** [comment]
With v0.2.3 I am getting another error:
'''
2022-12-18 11:48:02.753 DEBUG (MainThread) [custom_components.uniled.lib.ble_banlanx1] SP601E: Packet 2 - payload size: 8, payload so far: 23, message length: 23 (23)
2022-12-18 11:48:02.754 DEBUG (MainThread) [custom_components.uniled.lib.ble_banlanx1] SP601E: Good Status Message: 010100ff0a1e01ff000010010102ff0a1e0000ff001000
2022-12-18 11:48:02.754 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 1: Set Status: UNILEDStatus(power=True, mode=None, level=255, white=None, rgb=(255, 0, 0), rgb2=None, effect=1, fxtype=1, speed=10, length=30, direction=1, input=None, gain=16, chip_type=None, chip_order=0, segment_count=None, segment_length=None, extra={})
2022-12-18 11:48:02.754 DEBUG (MainThread) [custom_components.uniled.lib.classes] Channel 2: Set Status: UNILEDStatus(power=True, mode=None, level=255, white=None, rgb=(0, 255, 0), rgb2=None, effect=1, fxtype=1, speed=10, length=30, direction=0, input=None, gain=16, chip_type=None, chip_order=2, segment_count=None, segment_length=None, extra={})
2022-12-18 11:48:02.764 ERROR (MainThread) [root] A message handler raised an exception: bytearray index out of range.
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 796, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 860, in _parse_msg
    on_value_changed(message.path, self_interface["Value"])
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 152, in on_value_changed
    callback(bytearray(value))
  File "/config/custom_components/uniled/lib/ble_device.py", line 200, in _notification_handler
    new_master_state = self._model.async_decode_notifications(
  File "/config/custom_components/uniled/lib/ble_banlanx1.py", line 263, in async_decode_notifications
    mode=data[23] if master_power else BANLANX1_MODE_OFF,
IndexError: bytearray index out of range

2022-12-18 11:48:04.460 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Timeout waiting for status notification
2022-12-18 11:48:04.461 DEBUG (MainThread) [custom_components.uniled.coordinator] Finished fetching SP601E data in 9.556 seconds (success: False)
2022-12-18 11:48:04.461 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Stop
2022-12-18 11:48:04.461 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Disconnecting from device
2022-12-18 11:48:05.478 DEBUG (MainThread) [custom_components.uniled.lib.ble_device] SP601E: Stopped notifications from device

**Comment by VasiliyNovosad** [comment]
When both channels are switched off, then initialization is successful. But when one of channels is switched on, then I am getting such error

**Comment by monty68** [comment]
I know what the issue is, for some reason your device is sending a status with one byte less than what my SP601E  does.

I'll post a fix shortly

**Comment by monty68** [comment]
Please download, install and test v0.2.4 Beta

**Comment by VasiliyNovosad** [comment]
It works fine now. Thanks a lot!
